### ISSUE TITLE
Karta 'dras tillbaka' när man försöker flytta vyn

### ISSUE THREAD

**Issue by datalowe** [fahlstrm/pattern-adminweb#17]
Om man i kartan försöker dra åt något håll för att t ex ändra vilken del av en stad som syns så går det bra i någon sekund, men efter en kort stund 'hoppar kartan tillbaka' till ursprungspositionen.

Kommentar från Frida om det:
> Jag gissar att det beror på att vi sätter city-center när man hämtar stad, och sedan när vi ritar ut kartan så plockas det värdet.
Och kartan subsc. på scooters vilka uppdateras var 5e sekund - så när den laddar om och ritar om kartan så "återställs" center till ursprungsvärdet för staden... 

Jag gissar att man skulle kunna använda en eller två properties på component- eller service-nivå (eller redux om ni använder det) som kartans centerpunktskoordinater sparas till när användaren interagerar med kartan, så matas de tillbaka till Leaflet när det sker uppdateringar. Nåt sånt. Men det är länge sen jag använde Leaflet, så jag har inte bra koll på hur deras API ser ut och hur enkelt/svårt det är att ange koordinater till det.

**Comment by jannikarlsson** [comment]
Center går redan åt båda håll, löses enkelt genom att flytta en rad som skriver stadens centrum som centrum i varje inläsning utan bara en gång.
