### ISSUE TITLE
Stadsbilder kommer 'ur fokus' när man svävar över stadsnamnet

### ISSUE THREAD

**Issue by datalowe** [fahlstrm/pattern-adminweb#19]
En småsak jag märkte, medan jag minns den: När man svävar över städernas text så tappas 'fokus' på bilderna. Ifall det verkar krångligt att fixa så strunta i det, vi har ju annat att göra också

> Jag hade velat ha ett "filter" över bilden, typ grått så de passar in och sedan vid hoover så ska bildens färger bli klararare, dvs filtetet har lägre opacitet. 
MEN så har jag ju ett p-element i med högre z-index. Så hovrar man över det - så påverkas inte parent... 

Jag tror att du kan göra så att regeln är baserad på 'hover en nivå upp'. Ex om du har .cool-img:hover { så vill du ha .container-div:hover > .cool.img {, eller så behöver du gå flera nivåer upp, beroende på vilken som är närmsta gemensamma parent för p-elementet och img-elementet

**Comment by fahlstrm** [comment]
Lagt till .overlay som skapar div ovan.
