### ISSUE TITLE
Filtrera bort oavslutade resor från loggen

### ISSUE THREAD

**Issue by jannikarlsson** [fahlstrm/pattern-adminweb#22]
Avslutad resa: 
```{"id":10,"customer_id":5,"scooter_id":912,"start_time":"2021-11-30 18:02:51","end_time":"2021-11-30 18:10:51","start_lat":"59.893473","start_lon":"17.600219","end_lat":"59.861925","end_lon":"17.680427","start_cost":"20.00","travel_cost":"20.00","parking_cost":"20.00","total_cost":"60.00","username":"mosbth","payment_terms":"prepaid"}```

Oavslutad resa:
```{"id":12,"customer_id":130,"scooter_id":130,"start_time":"2021-12-07 18:28:11","end_time":null,"start_lat":"58.397189","start_lon":"13.808095","end_lat":null,"end_lon":null,"start_cost":"0.00","travel_cost":"0.00","parking_cost":"0.00","total_cost":"0.00","username":"bbispo3g","payment_terms":"prepaid"}```

Förmodligen enklast att filtrera bort alla som inte har end_time t ex.

**Comment by fahlstrm** [comment]
Sorteras i backend. Vid hämtning av loggar hämtas bara redan avslutade.
