### ISSUE TITLE
Justera oauth så att den kollar i admintabellen i stället för customer

### ISSUE THREAD

**Issue by jannikarlsson** [fahlstrm/pattern-adminweb#30]
Behörighetskontrollen i admin måste gå på en annan route för att kontrolleras mot admintabellen så att inte kunder kan logga in och skapa konto, ändra till `/auth/github/redirect/admin` i http-service och kontrollera i routen att user_type är admin (ta bort customer).

**Comment by fahlstrm** [comment]
Tagit bort customer i auth.service rad 38. Kompletterat redirect/admin routen.
