### ISSUE TITLE
Cities kan 'saknas'

### ISSUE THREAD

**Issue by datalowe** [fahlstrm/pattern-adminweb#32]
Jag märkte när jag testade att ibland när jag gick in på 'städer'-routen/vyn så kom inte städerna upp. Det här beror på att städerna bara hämtas från backend en gång, när [cityservice instansieras](https://github.com/fahlstrm/pattern-adminweb/blob/master/src/app/services/city.service.ts): 

```js
  constructor(private httpService: HttpService) { 
    this.loadCitites();
  }
```

När de sen hämtas via [CityComponents template](https://github.com/fahlstrm/pattern-adminweb/blob/master/src/app/components/routes/cities/cities.component.html) så används bara de städer som laddades in vid instansiering.

Om CityService instansieras innan användaren loggar in kan det därför bli så att städerna 'saknas', eftersom backend kräver att användaren är inloggad även för /cities-ändpunkten.

Jag gissar att det går att lösa det här genom att göra så att `get cities`-metoden i CityService triggar en förfrågan till backend för uppdatering, liknande som görs på andra services. Men om det är meckigt kan vi annars i backend ändra så att `cities`-ändpunkten är tillgänglig även för ej inloggade klienter, säg bara till isf.

**Comment by fahlstrm** [comment]
Har justerat så att body subscribar korrekt värde och city bör nu laddas in vid rätt tillfälle när cookie är satt. 
Kan inte själv återskapa felet, så testa gärna. Öppna upp issue igen om fel kvarstår!
